/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.framework.webClient.dispatch.up.bean;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.11.0)", date = "2019-04-24")
public class KLDTO implements org.apache.thrift.TBase<KLDTO, KLDTO._Fields>, java.io.Serializable, Cloneable, Comparable<KLDTO> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("KLDTO");

  private static final org.apache.thrift.protocol.TField ZDBH_FIELD_DESC = new org.apache.thrift.protocol.TField("zdbh", org.apache.thrift.protocol.TType.I16, (short)1);
  private static final org.apache.thrift.protocol.TField SSXBS_FIELD_DESC = new org.apache.thrift.protocol.TField("ssxbs", org.apache.thrift.protocol.TType.BYTE, (short)2);
  private static final org.apache.thrift.protocol.TField SXCBS_FIELD_DESC = new org.apache.thrift.protocol.TField("sxcbs", org.apache.thrift.protocol.TType.BYTE, (short)3);
  private static final org.apache.thrift.protocol.TField BCBS_FIELD_DESC = new org.apache.thrift.protocol.TField("bcbs", org.apache.thrift.protocol.TType.BYTE, (short)4);
  private static final org.apache.thrift.protocol.TField CJSJC_FIELD_DESC = new org.apache.thrift.protocol.TField("cjsjc", org.apache.thrift.protocol.TType.I32, (short)5);
  private static final org.apache.thrift.protocol.TField SBID_FIELD_DESC = new org.apache.thrift.protocol.TField("sbid", org.apache.thrift.protocol.TType.STRING, (short)6);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new KLDTOStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new KLDTOTupleSchemeFactory();

  public short zdbh; // required
  public byte ssxbs; // required
  public byte sxcbs; // required
  public byte bcbs; // required
  public int cjsjc; // required
  public java.lang.String sbid; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    ZDBH((short)1, "zdbh"),
    SSXBS((short)2, "ssxbs"),
    SXCBS((short)3, "sxcbs"),
    BCBS((short)4, "bcbs"),
    CJSJC((short)5, "cjsjc"),
    SBID((short)6, "sbid");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // ZDBH
          return ZDBH;
        case 2: // SSXBS
          return SSXBS;
        case 3: // SXCBS
          return SXCBS;
        case 4: // BCBS
          return BCBS;
        case 5: // CJSJC
          return CJSJC;
        case 6: // SBID
          return SBID;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __ZDBH_ISSET_ID = 0;
  private static final int __SSXBS_ISSET_ID = 1;
  private static final int __SXCBS_ISSET_ID = 2;
  private static final int __BCBS_ISSET_ID = 3;
  private static final int __CJSJC_ISSET_ID = 4;
  private byte __isset_bitfield = 0;
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.ZDBH, new org.apache.thrift.meta_data.FieldMetaData("zdbh", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I16)));
    tmpMap.put(_Fields.SSXBS, new org.apache.thrift.meta_data.FieldMetaData("ssxbs", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.BYTE)));
    tmpMap.put(_Fields.SXCBS, new org.apache.thrift.meta_data.FieldMetaData("sxcbs", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.BYTE)));
    tmpMap.put(_Fields.BCBS, new org.apache.thrift.meta_data.FieldMetaData("bcbs", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.BYTE)));
    tmpMap.put(_Fields.CJSJC, new org.apache.thrift.meta_data.FieldMetaData("cjsjc", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.SBID, new org.apache.thrift.meta_data.FieldMetaData("sbid", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(KLDTO.class, metaDataMap);
  }

  public KLDTO() {
  }

  public KLDTO(
    short zdbh,
    byte ssxbs,
    byte sxcbs,
    byte bcbs,
    int cjsjc,
    java.lang.String sbid)
  {
    this();
    this.zdbh = zdbh;
    setZdbhIsSet(true);
    this.ssxbs = ssxbs;
    setSsxbsIsSet(true);
    this.sxcbs = sxcbs;
    setSxcbsIsSet(true);
    this.bcbs = bcbs;
    setBcbsIsSet(true);
    this.cjsjc = cjsjc;
    setCjsjcIsSet(true);
    this.sbid = sbid;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public KLDTO(KLDTO other) {
    __isset_bitfield = other.__isset_bitfield;
    this.zdbh = other.zdbh;
    this.ssxbs = other.ssxbs;
    this.sxcbs = other.sxcbs;
    this.bcbs = other.bcbs;
    this.cjsjc = other.cjsjc;
    if (other.isSetSbid()) {
      this.sbid = other.sbid;
    }
  }

  public KLDTO deepCopy() {
    return new KLDTO(this);
  }

  @Override
  public void clear() {
    setZdbhIsSet(false);
    this.zdbh = 0;
    setSsxbsIsSet(false);
    this.ssxbs = 0;
    setSxcbsIsSet(false);
    this.sxcbs = 0;
    setBcbsIsSet(false);
    this.bcbs = 0;
    setCjsjcIsSet(false);
    this.cjsjc = 0;
    this.sbid = null;
  }

  public short getZdbh() {
    return this.zdbh;
  }

  public KLDTO setZdbh(short zdbh) {
    this.zdbh = zdbh;
    setZdbhIsSet(true);
    return this;
  }

  public void unsetZdbh() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __ZDBH_ISSET_ID);
  }

  /** Returns true if field zdbh is set (has been assigned a value) and false otherwise */
  public boolean isSetZdbh() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __ZDBH_ISSET_ID);
  }

  public void setZdbhIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __ZDBH_ISSET_ID, value);
  }

  public byte getSsxbs() {
    return this.ssxbs;
  }

  public KLDTO setSsxbs(byte ssxbs) {
    this.ssxbs = ssxbs;
    setSsxbsIsSet(true);
    return this;
  }

  public void unsetSsxbs() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __SSXBS_ISSET_ID);
  }

  /** Returns true if field ssxbs is set (has been assigned a value) and false otherwise */
  public boolean isSetSsxbs() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __SSXBS_ISSET_ID);
  }

  public void setSsxbsIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __SSXBS_ISSET_ID, value);
  }

  public byte getSxcbs() {
    return this.sxcbs;
  }

  public KLDTO setSxcbs(byte sxcbs) {
    this.sxcbs = sxcbs;
    setSxcbsIsSet(true);
    return this;
  }

  public void unsetSxcbs() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __SXCBS_ISSET_ID);
  }

  /** Returns true if field sxcbs is set (has been assigned a value) and false otherwise */
  public boolean isSetSxcbs() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __SXCBS_ISSET_ID);
  }

  public void setSxcbsIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __SXCBS_ISSET_ID, value);
  }

  public byte getBcbs() {
    return this.bcbs;
  }

  public KLDTO setBcbs(byte bcbs) {
    this.bcbs = bcbs;
    setBcbsIsSet(true);
    return this;
  }

  public void unsetBcbs() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __BCBS_ISSET_ID);
  }

  /** Returns true if field bcbs is set (has been assigned a value) and false otherwise */
  public boolean isSetBcbs() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __BCBS_ISSET_ID);
  }

  public void setBcbsIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __BCBS_ISSET_ID, value);
  }

  public int getCjsjc() {
    return this.cjsjc;
  }

  public KLDTO setCjsjc(int cjsjc) {
    this.cjsjc = cjsjc;
    setCjsjcIsSet(true);
    return this;
  }

  public void unsetCjsjc() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __CJSJC_ISSET_ID);
  }

  /** Returns true if field cjsjc is set (has been assigned a value) and false otherwise */
  public boolean isSetCjsjc() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __CJSJC_ISSET_ID);
  }

  public void setCjsjcIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __CJSJC_ISSET_ID, value);
  }

  public java.lang.String getSbid() {
    return this.sbid;
  }

  public KLDTO setSbid(java.lang.String sbid) {
    this.sbid = sbid;
    return this;
  }

  public void unsetSbid() {
    this.sbid = null;
  }

  /** Returns true if field sbid is set (has been assigned a value) and false otherwise */
  public boolean isSetSbid() {
    return this.sbid != null;
  }

  public void setSbidIsSet(boolean value) {
    if (!value) {
      this.sbid = null;
    }
  }

  public void setFieldValue(_Fields field, java.lang.Object value) {
    switch (field) {
    case ZDBH:
      if (value == null) {
        unsetZdbh();
      } else {
        setZdbh((java.lang.Short)value);
      }
      break;

    case SSXBS:
      if (value == null) {
        unsetSsxbs();
      } else {
        setSsxbs((java.lang.Byte)value);
      }
      break;

    case SXCBS:
      if (value == null) {
        unsetSxcbs();
      } else {
        setSxcbs((java.lang.Byte)value);
      }
      break;

    case BCBS:
      if (value == null) {
        unsetBcbs();
      } else {
        setBcbs((java.lang.Byte)value);
      }
      break;

    case CJSJC:
      if (value == null) {
        unsetCjsjc();
      } else {
        setCjsjc((java.lang.Integer)value);
      }
      break;

    case SBID:
      if (value == null) {
        unsetSbid();
      } else {
        setSbid((java.lang.String)value);
      }
      break;

    }
  }

  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case ZDBH:
      return getZdbh();

    case SSXBS:
      return getSsxbs();

    case SXCBS:
      return getSxcbs();

    case BCBS:
      return getBcbs();

    case CJSJC:
      return getCjsjc();

    case SBID:
      return getSbid();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case ZDBH:
      return isSetZdbh();
    case SSXBS:
      return isSetSsxbs();
    case SXCBS:
      return isSetSxcbs();
    case BCBS:
      return isSetBcbs();
    case CJSJC:
      return isSetCjsjc();
    case SBID:
      return isSetSbid();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that == null)
      return false;
    if (that instanceof KLDTO)
      return this.equals((KLDTO)that);
    return false;
  }

  public boolean equals(KLDTO that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_zdbh = true;
    boolean that_present_zdbh = true;
    if (this_present_zdbh || that_present_zdbh) {
      if (!(this_present_zdbh && that_present_zdbh))
        return false;
      if (this.zdbh != that.zdbh)
        return false;
    }

    boolean this_present_ssxbs = true;
    boolean that_present_ssxbs = true;
    if (this_present_ssxbs || that_present_ssxbs) {
      if (!(this_present_ssxbs && that_present_ssxbs))
        return false;
      if (this.ssxbs != that.ssxbs)
        return false;
    }

    boolean this_present_sxcbs = true;
    boolean that_present_sxcbs = true;
    if (this_present_sxcbs || that_present_sxcbs) {
      if (!(this_present_sxcbs && that_present_sxcbs))
        return false;
      if (this.sxcbs != that.sxcbs)
        return false;
    }

    boolean this_present_bcbs = true;
    boolean that_present_bcbs = true;
    if (this_present_bcbs || that_present_bcbs) {
      if (!(this_present_bcbs && that_present_bcbs))
        return false;
      if (this.bcbs != that.bcbs)
        return false;
    }

    boolean this_present_cjsjc = true;
    boolean that_present_cjsjc = true;
    if (this_present_cjsjc || that_present_cjsjc) {
      if (!(this_present_cjsjc && that_present_cjsjc))
        return false;
      if (this.cjsjc != that.cjsjc)
        return false;
    }

    boolean this_present_sbid = true && this.isSetSbid();
    boolean that_present_sbid = true && that.isSetSbid();
    if (this_present_sbid || that_present_sbid) {
      if (!(this_present_sbid && that_present_sbid))
        return false;
      if (!this.sbid.equals(that.sbid))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + zdbh;

    hashCode = hashCode * 8191 + (int) (ssxbs);

    hashCode = hashCode * 8191 + (int) (sxcbs);

    hashCode = hashCode * 8191 + (int) (bcbs);

    hashCode = hashCode * 8191 + cjsjc;

    hashCode = hashCode * 8191 + ((isSetSbid()) ? 131071 : 524287);
    if (isSetSbid())
      hashCode = hashCode * 8191 + sbid.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(KLDTO other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.valueOf(isSetZdbh()).compareTo(other.isSetZdbh());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetZdbh()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.zdbh, other.zdbh);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetSsxbs()).compareTo(other.isSetSsxbs());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetSsxbs()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.ssxbs, other.ssxbs);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetSxcbs()).compareTo(other.isSetSxcbs());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetSxcbs()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.sxcbs, other.sxcbs);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetBcbs()).compareTo(other.isSetBcbs());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetBcbs()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.bcbs, other.bcbs);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetCjsjc()).compareTo(other.isSetCjsjc());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCjsjc()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.cjsjc, other.cjsjc);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetSbid()).compareTo(other.isSetSbid());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetSbid()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.sbid, other.sbid);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("KLDTO(");
    boolean first = true;

    sb.append("zdbh:");
    sb.append(this.zdbh);
    first = false;
    if (!first) sb.append(", ");
    sb.append("ssxbs:");
    sb.append(this.ssxbs);
    first = false;
    if (!first) sb.append(", ");
    sb.append("sxcbs:");
    sb.append(this.sxcbs);
    first = false;
    if (!first) sb.append(", ");
    sb.append("bcbs:");
    sb.append(this.bcbs);
    first = false;
    if (!first) sb.append(", ");
    sb.append("cjsjc:");
    sb.append(this.cjsjc);
    first = false;
    if (!first) sb.append(", ");
    sb.append("sbid:");
    if (this.sbid == null) {
      sb.append("null");
    } else {
      sb.append(this.sbid);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class KLDTOStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public KLDTOStandardScheme getScheme() {
      return new KLDTOStandardScheme();
    }
  }

  private static class KLDTOStandardScheme extends org.apache.thrift.scheme.StandardScheme<KLDTO> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, KLDTO struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // ZDBH
            if (schemeField.type == org.apache.thrift.protocol.TType.I16) {
              struct.zdbh = iprot.readI16();
              struct.setZdbhIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // SSXBS
            if (schemeField.type == org.apache.thrift.protocol.TType.BYTE) {
              struct.ssxbs = iprot.readByte();
              struct.setSsxbsIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // SXCBS
            if (schemeField.type == org.apache.thrift.protocol.TType.BYTE) {
              struct.sxcbs = iprot.readByte();
              struct.setSxcbsIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // BCBS
            if (schemeField.type == org.apache.thrift.protocol.TType.BYTE) {
              struct.bcbs = iprot.readByte();
              struct.setBcbsIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 5: // CJSJC
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.cjsjc = iprot.readI32();
              struct.setCjsjcIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 6: // SBID
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.sbid = iprot.readString();
              struct.setSbidIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, KLDTO struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(ZDBH_FIELD_DESC);
      oprot.writeI16(struct.zdbh);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(SSXBS_FIELD_DESC);
      oprot.writeByte(struct.ssxbs);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(SXCBS_FIELD_DESC);
      oprot.writeByte(struct.sxcbs);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(BCBS_FIELD_DESC);
      oprot.writeByte(struct.bcbs);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(CJSJC_FIELD_DESC);
      oprot.writeI32(struct.cjsjc);
      oprot.writeFieldEnd();
      if (struct.sbid != null) {
        oprot.writeFieldBegin(SBID_FIELD_DESC);
        oprot.writeString(struct.sbid);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class KLDTOTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public KLDTOTupleScheme getScheme() {
      return new KLDTOTupleScheme();
    }
  }

  private static class KLDTOTupleScheme extends org.apache.thrift.scheme.TupleScheme<KLDTO> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, KLDTO struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetZdbh()) {
        optionals.set(0);
      }
      if (struct.isSetSsxbs()) {
        optionals.set(1);
      }
      if (struct.isSetSxcbs()) {
        optionals.set(2);
      }
      if (struct.isSetBcbs()) {
        optionals.set(3);
      }
      if (struct.isSetCjsjc()) {
        optionals.set(4);
      }
      if (struct.isSetSbid()) {
        optionals.set(5);
      }
      oprot.writeBitSet(optionals, 6);
      if (struct.isSetZdbh()) {
        oprot.writeI16(struct.zdbh);
      }
      if (struct.isSetSsxbs()) {
        oprot.writeByte(struct.ssxbs);
      }
      if (struct.isSetSxcbs()) {
        oprot.writeByte(struct.sxcbs);
      }
      if (struct.isSetBcbs()) {
        oprot.writeByte(struct.bcbs);
      }
      if (struct.isSetCjsjc()) {
        oprot.writeI32(struct.cjsjc);
      }
      if (struct.isSetSbid()) {
        oprot.writeString(struct.sbid);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, KLDTO struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(6);
      if (incoming.get(0)) {
        struct.zdbh = iprot.readI16();
        struct.setZdbhIsSet(true);
      }
      if (incoming.get(1)) {
        struct.ssxbs = iprot.readByte();
        struct.setSsxbsIsSet(true);
      }
      if (incoming.get(2)) {
        struct.sxcbs = iprot.readByte();
        struct.setSxcbsIsSet(true);
      }
      if (incoming.get(3)) {
        struct.bcbs = iprot.readByte();
        struct.setBcbsIsSet(true);
      }
      if (incoming.get(4)) {
        struct.cjsjc = iprot.readI32();
        struct.setCjsjcIsSet(true);
      }
      if (incoming.get(5)) {
        struct.sbid = iprot.readString();
        struct.setSbidIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

