/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.framework.webClient.dispatch.up.bean;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.11.0)", date = "2019-04-24")
public class SKSJDTO implements org.apache.thrift.TBase<SKSJDTO, SKSJDTO._Fields>, java.io.Serializable, Cloneable, Comparable<SKSJDTO> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("SKSJDTO");

  private static final org.apache.thrift.protocol.TField ACTION_CMDTYPE_FIELD_DESC = new org.apache.thrift.protocol.TField("actionCMDType", org.apache.thrift.protocol.TType.I32, (short)1);
  private static final org.apache.thrift.protocol.TField XLID_FIELD_DESC = new org.apache.thrift.protocol.TField("xlid", org.apache.thrift.protocol.TType.STRING, (short)2);
  private static final org.apache.thrift.protocol.TField XLBH_FIELD_DESC = new org.apache.thrift.protocol.TField("xlbh", org.apache.thrift.protocol.TType.STRING, (short)3);
  private static final org.apache.thrift.protocol.TField XLMC_FIELD_DESC = new org.apache.thrift.protocol.TField("xlmc", org.apache.thrift.protocol.TType.STRING, (short)4);
  private static final org.apache.thrift.protocol.TField CLID_FIELD_DESC = new org.apache.thrift.protocol.TField("clid", org.apache.thrift.protocol.TType.STRING, (short)5);
  private static final org.apache.thrift.protocol.TField EMP_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("empId", org.apache.thrift.protocol.TType.STRING, (short)6);
  private static final org.apache.thrift.protocol.TField SBSXZCH_FIELD_DESC = new org.apache.thrift.protocol.TField("sbsxzch", org.apache.thrift.protocol.TType.STRING, (short)7);
  private static final org.apache.thrift.protocol.TField SKSJ_FIELD_DESC = new org.apache.thrift.protocol.TField("sksj", org.apache.thrift.protocol.TType.I32, (short)8);
  private static final org.apache.thrift.protocol.TField JD_FIELD_DESC = new org.apache.thrift.protocol.TField("jd", org.apache.thrift.protocol.TType.I32, (short)9);
  private static final org.apache.thrift.protocol.TField WD_FIELD_DESC = new org.apache.thrift.protocol.TField("wd", org.apache.thrift.protocol.TType.I32, (short)10);
  private static final org.apache.thrift.protocol.TField SSSD_FIELD_DESC = new org.apache.thrift.protocol.TField("sssd", org.apache.thrift.protocol.TType.BYTE, (short)11);
  private static final org.apache.thrift.protocol.TField FXJ_FIELD_DESC = new org.apache.thrift.protocol.TField("fxj", org.apache.thrift.protocol.TType.I16, (short)12);
  private static final org.apache.thrift.protocol.TField GD_FIELD_DESC = new org.apache.thrift.protocol.TField("gd", org.apache.thrift.protocol.TType.I16, (short)13);
  private static final org.apache.thrift.protocol.TField YYZT_FIELD_DESC = new org.apache.thrift.protocol.TField("yyzt", org.apache.thrift.protocol.TType.BYTE, (short)14);
  private static final org.apache.thrift.protocol.TField KH_FIELD_DESC = new org.apache.thrift.protocol.TField("kh", org.apache.thrift.protocol.TType.STRING, (short)15);
  private static final org.apache.thrift.protocol.TField KQLX_FIELD_DESC = new org.apache.thrift.protocol.TField("kqlx", org.apache.thrift.protocol.TType.BYTE, (short)16);
  private static final org.apache.thrift.protocol.TField KQFS_FIELD_DESC = new org.apache.thrift.protocol.TField("kqfs", org.apache.thrift.protocol.TType.BYTE, (short)17);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new SKSJDTOStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new SKSJDTOTupleSchemeFactory();

  /**
   * 
   * @see ActionCMDType
   */
  public ActionCMDType actionCMDType; // required
  public java.lang.String xlid; // required
  public java.lang.String xlbh; // required
  public java.lang.String xlmc; // required
  public java.lang.String clid; // required
  public java.lang.String empId; // required
  public java.lang.String sbsxzch; // required
  public int sksj; // required
  public int jd; // required
  public int wd; // required
  public byte sssd; // required
  public short fxj; // required
  public short gd; // required
  public byte yyzt; // required
  public java.lang.String kh; // required
  public byte kqlx; // required
  public byte kqfs; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    /**
     * 
     * @see ActionCMDType
     */
    ACTION_CMDTYPE((short)1, "actionCMDType"),
    XLID((short)2, "xlid"),
    XLBH((short)3, "xlbh"),
    XLMC((short)4, "xlmc"),
    CLID((short)5, "clid"),
    EMP_ID((short)6, "empId"),
    SBSXZCH((short)7, "sbsxzch"),
    SKSJ((short)8, "sksj"),
    JD((short)9, "jd"),
    WD((short)10, "wd"),
    SSSD((short)11, "sssd"),
    FXJ((short)12, "fxj"),
    GD((short)13, "gd"),
    YYZT((short)14, "yyzt"),
    KH((short)15, "kh"),
    KQLX((short)16, "kqlx"),
    KQFS((short)17, "kqfs");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // ACTION_CMDTYPE
          return ACTION_CMDTYPE;
        case 2: // XLID
          return XLID;
        case 3: // XLBH
          return XLBH;
        case 4: // XLMC
          return XLMC;
        case 5: // CLID
          return CLID;
        case 6: // EMP_ID
          return EMP_ID;
        case 7: // SBSXZCH
          return SBSXZCH;
        case 8: // SKSJ
          return SKSJ;
        case 9: // JD
          return JD;
        case 10: // WD
          return WD;
        case 11: // SSSD
          return SSSD;
        case 12: // FXJ
          return FXJ;
        case 13: // GD
          return GD;
        case 14: // YYZT
          return YYZT;
        case 15: // KH
          return KH;
        case 16: // KQLX
          return KQLX;
        case 17: // KQFS
          return KQFS;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __SKSJ_ISSET_ID = 0;
  private static final int __JD_ISSET_ID = 1;
  private static final int __WD_ISSET_ID = 2;
  private static final int __SSSD_ISSET_ID = 3;
  private static final int __FXJ_ISSET_ID = 4;
  private static final int __GD_ISSET_ID = 5;
  private static final int __YYZT_ISSET_ID = 6;
  private static final int __KQLX_ISSET_ID = 7;
  private static final int __KQFS_ISSET_ID = 8;
  private short __isset_bitfield = 0;
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.ACTION_CMDTYPE, new org.apache.thrift.meta_data.FieldMetaData("actionCMDType", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.EnumMetaData(org.apache.thrift.protocol.TType.ENUM, ActionCMDType.class)));
    tmpMap.put(_Fields.XLID, new org.apache.thrift.meta_data.FieldMetaData("xlid", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.XLBH, new org.apache.thrift.meta_data.FieldMetaData("xlbh", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.XLMC, new org.apache.thrift.meta_data.FieldMetaData("xlmc", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.CLID, new org.apache.thrift.meta_data.FieldMetaData("clid", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.EMP_ID, new org.apache.thrift.meta_data.FieldMetaData("empId", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.SBSXZCH, new org.apache.thrift.meta_data.FieldMetaData("sbsxzch", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.SKSJ, new org.apache.thrift.meta_data.FieldMetaData("sksj", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.JD, new org.apache.thrift.meta_data.FieldMetaData("jd", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.WD, new org.apache.thrift.meta_data.FieldMetaData("wd", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.SSSD, new org.apache.thrift.meta_data.FieldMetaData("sssd", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.BYTE)));
    tmpMap.put(_Fields.FXJ, new org.apache.thrift.meta_data.FieldMetaData("fxj", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I16)));
    tmpMap.put(_Fields.GD, new org.apache.thrift.meta_data.FieldMetaData("gd", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I16)));
    tmpMap.put(_Fields.YYZT, new org.apache.thrift.meta_data.FieldMetaData("yyzt", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.BYTE)));
    tmpMap.put(_Fields.KH, new org.apache.thrift.meta_data.FieldMetaData("kh", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.KQLX, new org.apache.thrift.meta_data.FieldMetaData("kqlx", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.BYTE)));
    tmpMap.put(_Fields.KQFS, new org.apache.thrift.meta_data.FieldMetaData("kqfs", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.BYTE)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(SKSJDTO.class, metaDataMap);
  }

  public SKSJDTO() {
  }

  public SKSJDTO(
    ActionCMDType actionCMDType,
    java.lang.String xlid,
    java.lang.String xlbh,
    java.lang.String xlmc,
    java.lang.String clid,
    java.lang.String empId,
    java.lang.String sbsxzch,
    int sksj,
    int jd,
    int wd,
    byte sssd,
    short fxj,
    short gd,
    byte yyzt,
    java.lang.String kh,
    byte kqlx,
    byte kqfs)
  {
    this();
    this.actionCMDType = actionCMDType;
    this.xlid = xlid;
    this.xlbh = xlbh;
    this.xlmc = xlmc;
    this.clid = clid;
    this.empId = empId;
    this.sbsxzch = sbsxzch;
    this.sksj = sksj;
    setSksjIsSet(true);
    this.jd = jd;
    setJdIsSet(true);
    this.wd = wd;
    setWdIsSet(true);
    this.sssd = sssd;
    setSssdIsSet(true);
    this.fxj = fxj;
    setFxjIsSet(true);
    this.gd = gd;
    setGdIsSet(true);
    this.yyzt = yyzt;
    setYyztIsSet(true);
    this.kh = kh;
    this.kqlx = kqlx;
    setKqlxIsSet(true);
    this.kqfs = kqfs;
    setKqfsIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public SKSJDTO(SKSJDTO other) {
    __isset_bitfield = other.__isset_bitfield;
    if (other.isSetActionCMDType()) {
      this.actionCMDType = other.actionCMDType;
    }
    if (other.isSetXlid()) {
      this.xlid = other.xlid;
    }
    if (other.isSetXlbh()) {
      this.xlbh = other.xlbh;
    }
    if (other.isSetXlmc()) {
      this.xlmc = other.xlmc;
    }
    if (other.isSetClid()) {
      this.clid = other.clid;
    }
    if (other.isSetEmpId()) {
      this.empId = other.empId;
    }
    if (other.isSetSbsxzch()) {
      this.sbsxzch = other.sbsxzch;
    }
    this.sksj = other.sksj;
    this.jd = other.jd;
    this.wd = other.wd;
    this.sssd = other.sssd;
    this.fxj = other.fxj;
    this.gd = other.gd;
    this.yyzt = other.yyzt;
    if (other.isSetKh()) {
      this.kh = other.kh;
    }
    this.kqlx = other.kqlx;
    this.kqfs = other.kqfs;
  }

  public SKSJDTO deepCopy() {
    return new SKSJDTO(this);
  }

  @Override
  public void clear() {
    this.actionCMDType = null;
    this.xlid = null;
    this.xlbh = null;
    this.xlmc = null;
    this.clid = null;
    this.empId = null;
    this.sbsxzch = null;
    setSksjIsSet(false);
    this.sksj = 0;
    setJdIsSet(false);
    this.jd = 0;
    setWdIsSet(false);
    this.wd = 0;
    setSssdIsSet(false);
    this.sssd = 0;
    setFxjIsSet(false);
    this.fxj = 0;
    setGdIsSet(false);
    this.gd = 0;
    setYyztIsSet(false);
    this.yyzt = 0;
    this.kh = null;
    setKqlxIsSet(false);
    this.kqlx = 0;
    setKqfsIsSet(false);
    this.kqfs = 0;
  }

  /**
   * 
   * @see ActionCMDType
   */
  public ActionCMDType getActionCMDType() {
    return this.actionCMDType;
  }

  /**
   * 
   * @see ActionCMDType
   */
  public SKSJDTO setActionCMDType(ActionCMDType actionCMDType) {
    this.actionCMDType = actionCMDType;
    return this;
  }

  public void unsetActionCMDType() {
    this.actionCMDType = null;
  }

  /** Returns true if field actionCMDType is set (has been assigned a value) and false otherwise */
  public boolean isSetActionCMDType() {
    return this.actionCMDType != null;
  }

  public void setActionCMDTypeIsSet(boolean value) {
    if (!value) {
      this.actionCMDType = null;
    }
  }

  public java.lang.String getXlid() {
    return this.xlid;
  }

  public SKSJDTO setXlid(java.lang.String xlid) {
    this.xlid = xlid;
    return this;
  }

  public void unsetXlid() {
    this.xlid = null;
  }

  /** Returns true if field xlid is set (has been assigned a value) and false otherwise */
  public boolean isSetXlid() {
    return this.xlid != null;
  }

  public void setXlidIsSet(boolean value) {
    if (!value) {
      this.xlid = null;
    }
  }

  public java.lang.String getXlbh() {
    return this.xlbh;
  }

  public SKSJDTO setXlbh(java.lang.String xlbh) {
    this.xlbh = xlbh;
    return this;
  }

  public void unsetXlbh() {
    this.xlbh = null;
  }

  /** Returns true if field xlbh is set (has been assigned a value) and false otherwise */
  public boolean isSetXlbh() {
    return this.xlbh != null;
  }

  public void setXlbhIsSet(boolean value) {
    if (!value) {
      this.xlbh = null;
    }
  }

  public java.lang.String getXlmc() {
    return this.xlmc;
  }

  public SKSJDTO setXlmc(java.lang.String xlmc) {
    this.xlmc = xlmc;
    return this;
  }

  public void unsetXlmc() {
    this.xlmc = null;
  }

  /** Returns true if field xlmc is set (has been assigned a value) and false otherwise */
  public boolean isSetXlmc() {
    return this.xlmc != null;
  }

  public void setXlmcIsSet(boolean value) {
    if (!value) {
      this.xlmc = null;
    }
  }

  public java.lang.String getClid() {
    return this.clid;
  }

  public SKSJDTO setClid(java.lang.String clid) {
    this.clid = clid;
    return this;
  }

  public void unsetClid() {
    this.clid = null;
  }

  /** Returns true if field clid is set (has been assigned a value) and false otherwise */
  public boolean isSetClid() {
    return this.clid != null;
  }

  public void setClidIsSet(boolean value) {
    if (!value) {
      this.clid = null;
    }
  }

  public java.lang.String getEmpId() {
    return this.empId;
  }

  public SKSJDTO setEmpId(java.lang.String empId) {
    this.empId = empId;
    return this;
  }

  public void unsetEmpId() {
    this.empId = null;
  }

  /** Returns true if field empId is set (has been assigned a value) and false otherwise */
  public boolean isSetEmpId() {
    return this.empId != null;
  }

  public void setEmpIdIsSet(boolean value) {
    if (!value) {
      this.empId = null;
    }
  }

  public java.lang.String getSbsxzch() {
    return this.sbsxzch;
  }

  public SKSJDTO setSbsxzch(java.lang.String sbsxzch) {
    this.sbsxzch = sbsxzch;
    return this;
  }

  public void unsetSbsxzch() {
    this.sbsxzch = null;
  }

  /** Returns true if field sbsxzch is set (has been assigned a value) and false otherwise */
  public boolean isSetSbsxzch() {
    return this.sbsxzch != null;
  }

  public void setSbsxzchIsSet(boolean value) {
    if (!value) {
      this.sbsxzch = null;
    }
  }

  public int getSksj() {
    return this.sksj;
  }

  public SKSJDTO setSksj(int sksj) {
    this.sksj = sksj;
    setSksjIsSet(true);
    return this;
  }

  public void unsetSksj() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __SKSJ_ISSET_ID);
  }

  /** Returns true if field sksj is set (has been assigned a value) and false otherwise */
  public boolean isSetSksj() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __SKSJ_ISSET_ID);
  }

  public void setSksjIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __SKSJ_ISSET_ID, value);
  }

  public int getJd() {
    return this.jd;
  }

  public SKSJDTO setJd(int jd) {
    this.jd = jd;
    setJdIsSet(true);
    return this;
  }

  public void unsetJd() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __JD_ISSET_ID);
  }

  /** Returns true if field jd is set (has been assigned a value) and false otherwise */
  public boolean isSetJd() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __JD_ISSET_ID);
  }

  public void setJdIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __JD_ISSET_ID, value);
  }

  public int getWd() {
    return this.wd;
  }

  public SKSJDTO setWd(int wd) {
    this.wd = wd;
    setWdIsSet(true);
    return this;
  }

  public void unsetWd() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __WD_ISSET_ID);
  }

  /** Returns true if field wd is set (has been assigned a value) and false otherwise */
  public boolean isSetWd() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __WD_ISSET_ID);
  }

  public void setWdIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __WD_ISSET_ID, value);
  }

  public byte getSssd() {
    return this.sssd;
  }

  public SKSJDTO setSssd(byte sssd) {
    this.sssd = sssd;
    setSssdIsSet(true);
    return this;
  }

  public void unsetSssd() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __SSSD_ISSET_ID);
  }

  /** Returns true if field sssd is set (has been assigned a value) and false otherwise */
  public boolean isSetSssd() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __SSSD_ISSET_ID);
  }

  public void setSssdIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __SSSD_ISSET_ID, value);
  }

  public short getFxj() {
    return this.fxj;
  }

  public SKSJDTO setFxj(short fxj) {
    this.fxj = fxj;
    setFxjIsSet(true);
    return this;
  }

  public void unsetFxj() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __FXJ_ISSET_ID);
  }

  /** Returns true if field fxj is set (has been assigned a value) and false otherwise */
  public boolean isSetFxj() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __FXJ_ISSET_ID);
  }

  public void setFxjIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __FXJ_ISSET_ID, value);
  }

  public short getGd() {
    return this.gd;
  }

  public SKSJDTO setGd(short gd) {
    this.gd = gd;
    setGdIsSet(true);
    return this;
  }

  public void unsetGd() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __GD_ISSET_ID);
  }

  /** Returns true if field gd is set (has been assigned a value) and false otherwise */
  public boolean isSetGd() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __GD_ISSET_ID);
  }

  public void setGdIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __GD_ISSET_ID, value);
  }

  public byte getYyzt() {
    return this.yyzt;
  }

  public SKSJDTO setYyzt(byte yyzt) {
    this.yyzt = yyzt;
    setYyztIsSet(true);
    return this;
  }

  public void unsetYyzt() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __YYZT_ISSET_ID);
  }

  /** Returns true if field yyzt is set (has been assigned a value) and false otherwise */
  public boolean isSetYyzt() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __YYZT_ISSET_ID);
  }

  public void setYyztIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __YYZT_ISSET_ID, value);
  }

  public java.lang.String getKh() {
    return this.kh;
  }

  public SKSJDTO setKh(java.lang.String kh) {
    this.kh = kh;
    return this;
  }

  public void unsetKh() {
    this.kh = null;
  }

  /** Returns true if field kh is set (has been assigned a value) and false otherwise */
  public boolean isSetKh() {
    return this.kh != null;
  }

  public void setKhIsSet(boolean value) {
    if (!value) {
      this.kh = null;
    }
  }

  public byte getKqlx() {
    return this.kqlx;
  }

  public SKSJDTO setKqlx(byte kqlx) {
    this.kqlx = kqlx;
    setKqlxIsSet(true);
    return this;
  }

  public void unsetKqlx() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __KQLX_ISSET_ID);
  }

  /** Returns true if field kqlx is set (has been assigned a value) and false otherwise */
  public boolean isSetKqlx() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __KQLX_ISSET_ID);
  }

  public void setKqlxIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __KQLX_ISSET_ID, value);
  }

  public byte getKqfs() {
    return this.kqfs;
  }

  public SKSJDTO setKqfs(byte kqfs) {
    this.kqfs = kqfs;
    setKqfsIsSet(true);
    return this;
  }

  public void unsetKqfs() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __KQFS_ISSET_ID);
  }

  /** Returns true if field kqfs is set (has been assigned a value) and false otherwise */
  public boolean isSetKqfs() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __KQFS_ISSET_ID);
  }

  public void setKqfsIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __KQFS_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, java.lang.Object value) {
    switch (field) {
    case ACTION_CMDTYPE:
      if (value == null) {
        unsetActionCMDType();
      } else {
        setActionCMDType((ActionCMDType)value);
      }
      break;

    case XLID:
      if (value == null) {
        unsetXlid();
      } else {
        setXlid((java.lang.String)value);
      }
      break;

    case XLBH:
      if (value == null) {
        unsetXlbh();
      } else {
        setXlbh((java.lang.String)value);
      }
      break;

    case XLMC:
      if (value == null) {
        unsetXlmc();
      } else {
        setXlmc((java.lang.String)value);
      }
      break;

    case CLID:
      if (value == null) {
        unsetClid();
      } else {
        setClid((java.lang.String)value);
      }
      break;

    case EMP_ID:
      if (value == null) {
        unsetEmpId();
      } else {
        setEmpId((java.lang.String)value);
      }
      break;

    case SBSXZCH:
      if (value == null) {
        unsetSbsxzch();
      } else {
        setSbsxzch((java.lang.String)value);
      }
      break;

    case SKSJ:
      if (value == null) {
        unsetSksj();
      } else {
        setSksj((java.lang.Integer)value);
      }
      break;

    case JD:
      if (value == null) {
        unsetJd();
      } else {
        setJd((java.lang.Integer)value);
      }
      break;

    case WD:
      if (value == null) {
        unsetWd();
      } else {
        setWd((java.lang.Integer)value);
      }
      break;

    case SSSD:
      if (value == null) {
        unsetSssd();
      } else {
        setSssd((java.lang.Byte)value);
      }
      break;

    case FXJ:
      if (value == null) {
        unsetFxj();
      } else {
        setFxj((java.lang.Short)value);
      }
      break;

    case GD:
      if (value == null) {
        unsetGd();
      } else {
        setGd((java.lang.Short)value);
      }
      break;

    case YYZT:
      if (value == null) {
        unsetYyzt();
      } else {
        setYyzt((java.lang.Byte)value);
      }
      break;

    case KH:
      if (value == null) {
        unsetKh();
      } else {
        setKh((java.lang.String)value);
      }
      break;

    case KQLX:
      if (value == null) {
        unsetKqlx();
      } else {
        setKqlx((java.lang.Byte)value);
      }
      break;

    case KQFS:
      if (value == null) {
        unsetKqfs();
      } else {
        setKqfs((java.lang.Byte)value);
      }
      break;

    }
  }

  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case ACTION_CMDTYPE:
      return getActionCMDType();

    case XLID:
      return getXlid();

    case XLBH:
      return getXlbh();

    case XLMC:
      return getXlmc();

    case CLID:
      return getClid();

    case EMP_ID:
      return getEmpId();

    case SBSXZCH:
      return getSbsxzch();

    case SKSJ:
      return getSksj();

    case JD:
      return getJd();

    case WD:
      return getWd();

    case SSSD:
      return getSssd();

    case FXJ:
      return getFxj();

    case GD:
      return getGd();

    case YYZT:
      return getYyzt();

    case KH:
      return getKh();

    case KQLX:
      return getKqlx();

    case KQFS:
      return getKqfs();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case ACTION_CMDTYPE:
      return isSetActionCMDType();
    case XLID:
      return isSetXlid();
    case XLBH:
      return isSetXlbh();
    case XLMC:
      return isSetXlmc();
    case CLID:
      return isSetClid();
    case EMP_ID:
      return isSetEmpId();
    case SBSXZCH:
      return isSetSbsxzch();
    case SKSJ:
      return isSetSksj();
    case JD:
      return isSetJd();
    case WD:
      return isSetWd();
    case SSSD:
      return isSetSssd();
    case FXJ:
      return isSetFxj();
    case GD:
      return isSetGd();
    case YYZT:
      return isSetYyzt();
    case KH:
      return isSetKh();
    case KQLX:
      return isSetKqlx();
    case KQFS:
      return isSetKqfs();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that == null)
      return false;
    if (that instanceof SKSJDTO)
      return this.equals((SKSJDTO)that);
    return false;
  }

  public boolean equals(SKSJDTO that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_actionCMDType = true && this.isSetActionCMDType();
    boolean that_present_actionCMDType = true && that.isSetActionCMDType();
    if (this_present_actionCMDType || that_present_actionCMDType) {
      if (!(this_present_actionCMDType && that_present_actionCMDType))
        return false;
      if (!this.actionCMDType.equals(that.actionCMDType))
        return false;
    }

    boolean this_present_xlid = true && this.isSetXlid();
    boolean that_present_xlid = true && that.isSetXlid();
    if (this_present_xlid || that_present_xlid) {
      if (!(this_present_xlid && that_present_xlid))
        return false;
      if (!this.xlid.equals(that.xlid))
        return false;
    }

    boolean this_present_xlbh = true && this.isSetXlbh();
    boolean that_present_xlbh = true && that.isSetXlbh();
    if (this_present_xlbh || that_present_xlbh) {
      if (!(this_present_xlbh && that_present_xlbh))
        return false;
      if (!this.xlbh.equals(that.xlbh))
        return false;
    }

    boolean this_present_xlmc = true && this.isSetXlmc();
    boolean that_present_xlmc = true && that.isSetXlmc();
    if (this_present_xlmc || that_present_xlmc) {
      if (!(this_present_xlmc && that_present_xlmc))
        return false;
      if (!this.xlmc.equals(that.xlmc))
        return false;
    }

    boolean this_present_clid = true && this.isSetClid();
    boolean that_present_clid = true && that.isSetClid();
    if (this_present_clid || that_present_clid) {
      if (!(this_present_clid && that_present_clid))
        return false;
      if (!this.clid.equals(that.clid))
        return false;
    }

    boolean this_present_empId = true && this.isSetEmpId();
    boolean that_present_empId = true && that.isSetEmpId();
    if (this_present_empId || that_present_empId) {
      if (!(this_present_empId && that_present_empId))
        return false;
      if (!this.empId.equals(that.empId))
        return false;
    }

    boolean this_present_sbsxzch = true && this.isSetSbsxzch();
    boolean that_present_sbsxzch = true && that.isSetSbsxzch();
    if (this_present_sbsxzch || that_present_sbsxzch) {
      if (!(this_present_sbsxzch && that_present_sbsxzch))
        return false;
      if (!this.sbsxzch.equals(that.sbsxzch))
        return false;
    }

    boolean this_present_sksj = true;
    boolean that_present_sksj = true;
    if (this_present_sksj || that_present_sksj) {
      if (!(this_present_sksj && that_present_sksj))
        return false;
      if (this.sksj != that.sksj)
        return false;
    }

    boolean this_present_jd = true;
    boolean that_present_jd = true;
    if (this_present_jd || that_present_jd) {
      if (!(this_present_jd && that_present_jd))
        return false;
      if (this.jd != that.jd)
        return false;
    }

    boolean this_present_wd = true;
    boolean that_present_wd = true;
    if (this_present_wd || that_present_wd) {
      if (!(this_present_wd && that_present_wd))
        return false;
      if (this.wd != that.wd)
        return false;
    }

    boolean this_present_sssd = true;
    boolean that_present_sssd = true;
    if (this_present_sssd || that_present_sssd) {
      if (!(this_present_sssd && that_present_sssd))
        return false;
      if (this.sssd != that.sssd)
        return false;
    }

    boolean this_present_fxj = true;
    boolean that_present_fxj = true;
    if (this_present_fxj || that_present_fxj) {
      if (!(this_present_fxj && that_present_fxj))
        return false;
      if (this.fxj != that.fxj)
        return false;
    }

    boolean this_present_gd = true;
    boolean that_present_gd = true;
    if (this_present_gd || that_present_gd) {
      if (!(this_present_gd && that_present_gd))
        return false;
      if (this.gd != that.gd)
        return false;
    }

    boolean this_present_yyzt = true;
    boolean that_present_yyzt = true;
    if (this_present_yyzt || that_present_yyzt) {
      if (!(this_present_yyzt && that_present_yyzt))
        return false;
      if (this.yyzt != that.yyzt)
        return false;
    }

    boolean this_present_kh = true && this.isSetKh();
    boolean that_present_kh = true && that.isSetKh();
    if (this_present_kh || that_present_kh) {
      if (!(this_present_kh && that_present_kh))
        return false;
      if (!this.kh.equals(that.kh))
        return false;
    }

    boolean this_present_kqlx = true;
    boolean that_present_kqlx = true;
    if (this_present_kqlx || that_present_kqlx) {
      if (!(this_present_kqlx && that_present_kqlx))
        return false;
      if (this.kqlx != that.kqlx)
        return false;
    }

    boolean this_present_kqfs = true;
    boolean that_present_kqfs = true;
    if (this_present_kqfs || that_present_kqfs) {
      if (!(this_present_kqfs && that_present_kqfs))
        return false;
      if (this.kqfs != that.kqfs)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetActionCMDType()) ? 131071 : 524287);
    if (isSetActionCMDType())
      hashCode = hashCode * 8191 + actionCMDType.getValue();

    hashCode = hashCode * 8191 + ((isSetXlid()) ? 131071 : 524287);
    if (isSetXlid())
      hashCode = hashCode * 8191 + xlid.hashCode();

    hashCode = hashCode * 8191 + ((isSetXlbh()) ? 131071 : 524287);
    if (isSetXlbh())
      hashCode = hashCode * 8191 + xlbh.hashCode();

    hashCode = hashCode * 8191 + ((isSetXlmc()) ? 131071 : 524287);
    if (isSetXlmc())
      hashCode = hashCode * 8191 + xlmc.hashCode();

    hashCode = hashCode * 8191 + ((isSetClid()) ? 131071 : 524287);
    if (isSetClid())
      hashCode = hashCode * 8191 + clid.hashCode();

    hashCode = hashCode * 8191 + ((isSetEmpId()) ? 131071 : 524287);
    if (isSetEmpId())
      hashCode = hashCode * 8191 + empId.hashCode();

    hashCode = hashCode * 8191 + ((isSetSbsxzch()) ? 131071 : 524287);
    if (isSetSbsxzch())
      hashCode = hashCode * 8191 + sbsxzch.hashCode();

    hashCode = hashCode * 8191 + sksj;

    hashCode = hashCode * 8191 + jd;

    hashCode = hashCode * 8191 + wd;

    hashCode = hashCode * 8191 + (int) (sssd);

    hashCode = hashCode * 8191 + fxj;

    hashCode = hashCode * 8191 + gd;

    hashCode = hashCode * 8191 + (int) (yyzt);

    hashCode = hashCode * 8191 + ((isSetKh()) ? 131071 : 524287);
    if (isSetKh())
      hashCode = hashCode * 8191 + kh.hashCode();

    hashCode = hashCode * 8191 + (int) (kqlx);

    hashCode = hashCode * 8191 + (int) (kqfs);

    return hashCode;
  }

  @Override
  public int compareTo(SKSJDTO other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.valueOf(isSetActionCMDType()).compareTo(other.isSetActionCMDType());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetActionCMDType()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.actionCMDType, other.actionCMDType);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetXlid()).compareTo(other.isSetXlid());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetXlid()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.xlid, other.xlid);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetXlbh()).compareTo(other.isSetXlbh());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetXlbh()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.xlbh, other.xlbh);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetXlmc()).compareTo(other.isSetXlmc());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetXlmc()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.xlmc, other.xlmc);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetClid()).compareTo(other.isSetClid());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetClid()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.clid, other.clid);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetEmpId()).compareTo(other.isSetEmpId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetEmpId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.empId, other.empId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetSbsxzch()).compareTo(other.isSetSbsxzch());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetSbsxzch()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.sbsxzch, other.sbsxzch);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetSksj()).compareTo(other.isSetSksj());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetSksj()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.sksj, other.sksj);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetJd()).compareTo(other.isSetJd());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetJd()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.jd, other.jd);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetWd()).compareTo(other.isSetWd());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetWd()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.wd, other.wd);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetSssd()).compareTo(other.isSetSssd());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetSssd()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.sssd, other.sssd);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetFxj()).compareTo(other.isSetFxj());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetFxj()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.fxj, other.fxj);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetGd()).compareTo(other.isSetGd());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetGd()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.gd, other.gd);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetYyzt()).compareTo(other.isSetYyzt());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetYyzt()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.yyzt, other.yyzt);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetKh()).compareTo(other.isSetKh());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetKh()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.kh, other.kh);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetKqlx()).compareTo(other.isSetKqlx());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetKqlx()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.kqlx, other.kqlx);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetKqfs()).compareTo(other.isSetKqfs());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetKqfs()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.kqfs, other.kqfs);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("SKSJDTO(");
    boolean first = true;

    sb.append("actionCMDType:");
    if (this.actionCMDType == null) {
      sb.append("null");
    } else {
      sb.append(this.actionCMDType);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("xlid:");
    if (this.xlid == null) {
      sb.append("null");
    } else {
      sb.append(this.xlid);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("xlbh:");
    if (this.xlbh == null) {
      sb.append("null");
    } else {
      sb.append(this.xlbh);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("xlmc:");
    if (this.xlmc == null) {
      sb.append("null");
    } else {
      sb.append(this.xlmc);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("clid:");
    if (this.clid == null) {
      sb.append("null");
    } else {
      sb.append(this.clid);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("empId:");
    if (this.empId == null) {
      sb.append("null");
    } else {
      sb.append(this.empId);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("sbsxzch:");
    if (this.sbsxzch == null) {
      sb.append("null");
    } else {
      sb.append(this.sbsxzch);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("sksj:");
    sb.append(this.sksj);
    first = false;
    if (!first) sb.append(", ");
    sb.append("jd:");
    sb.append(this.jd);
    first = false;
    if (!first) sb.append(", ");
    sb.append("wd:");
    sb.append(this.wd);
    first = false;
    if (!first) sb.append(", ");
    sb.append("sssd:");
    sb.append(this.sssd);
    first = false;
    if (!first) sb.append(", ");
    sb.append("fxj:");
    sb.append(this.fxj);
    first = false;
    if (!first) sb.append(", ");
    sb.append("gd:");
    sb.append(this.gd);
    first = false;
    if (!first) sb.append(", ");
    sb.append("yyzt:");
    sb.append(this.yyzt);
    first = false;
    if (!first) sb.append(", ");
    sb.append("kh:");
    if (this.kh == null) {
      sb.append("null");
    } else {
      sb.append(this.kh);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("kqlx:");
    sb.append(this.kqlx);
    first = false;
    if (!first) sb.append(", ");
    sb.append("kqfs:");
    sb.append(this.kqfs);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class SKSJDTOStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public SKSJDTOStandardScheme getScheme() {
      return new SKSJDTOStandardScheme();
    }
  }

  private static class SKSJDTOStandardScheme extends org.apache.thrift.scheme.StandardScheme<SKSJDTO> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, SKSJDTO struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // ACTION_CMDTYPE
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.actionCMDType = ActionCMDType.findByValue(iprot.readI32());
              struct.setActionCMDTypeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // XLID
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.xlid = iprot.readString();
              struct.setXlidIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // XLBH
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.xlbh = iprot.readString();
              struct.setXlbhIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // XLMC
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.xlmc = iprot.readString();
              struct.setXlmcIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 5: // CLID
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.clid = iprot.readString();
              struct.setClidIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 6: // EMP_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.empId = iprot.readString();
              struct.setEmpIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 7: // SBSXZCH
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.sbsxzch = iprot.readString();
              struct.setSbsxzchIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 8: // SKSJ
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.sksj = iprot.readI32();
              struct.setSksjIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 9: // JD
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.jd = iprot.readI32();
              struct.setJdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 10: // WD
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.wd = iprot.readI32();
              struct.setWdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 11: // SSSD
            if (schemeField.type == org.apache.thrift.protocol.TType.BYTE) {
              struct.sssd = iprot.readByte();
              struct.setSssdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 12: // FXJ
            if (schemeField.type == org.apache.thrift.protocol.TType.I16) {
              struct.fxj = iprot.readI16();
              struct.setFxjIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 13: // GD
            if (schemeField.type == org.apache.thrift.protocol.TType.I16) {
              struct.gd = iprot.readI16();
              struct.setGdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 14: // YYZT
            if (schemeField.type == org.apache.thrift.protocol.TType.BYTE) {
              struct.yyzt = iprot.readByte();
              struct.setYyztIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 15: // KH
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.kh = iprot.readString();
              struct.setKhIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 16: // KQLX
            if (schemeField.type == org.apache.thrift.protocol.TType.BYTE) {
              struct.kqlx = iprot.readByte();
              struct.setKqlxIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 17: // KQFS
            if (schemeField.type == org.apache.thrift.protocol.TType.BYTE) {
              struct.kqfs = iprot.readByte();
              struct.setKqfsIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, SKSJDTO struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.actionCMDType != null) {
        oprot.writeFieldBegin(ACTION_CMDTYPE_FIELD_DESC);
        oprot.writeI32(struct.actionCMDType.getValue());
        oprot.writeFieldEnd();
      }
      if (struct.xlid != null) {
        oprot.writeFieldBegin(XLID_FIELD_DESC);
        oprot.writeString(struct.xlid);
        oprot.writeFieldEnd();
      }
      if (struct.xlbh != null) {
        oprot.writeFieldBegin(XLBH_FIELD_DESC);
        oprot.writeString(struct.xlbh);
        oprot.writeFieldEnd();
      }
      if (struct.xlmc != null) {
        oprot.writeFieldBegin(XLMC_FIELD_DESC);
        oprot.writeString(struct.xlmc);
        oprot.writeFieldEnd();
      }
      if (struct.clid != null) {
        oprot.writeFieldBegin(CLID_FIELD_DESC);
        oprot.writeString(struct.clid);
        oprot.writeFieldEnd();
      }
      if (struct.empId != null) {
        oprot.writeFieldBegin(EMP_ID_FIELD_DESC);
        oprot.writeString(struct.empId);
        oprot.writeFieldEnd();
      }
      if (struct.sbsxzch != null) {
        oprot.writeFieldBegin(SBSXZCH_FIELD_DESC);
        oprot.writeString(struct.sbsxzch);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(SKSJ_FIELD_DESC);
      oprot.writeI32(struct.sksj);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(JD_FIELD_DESC);
      oprot.writeI32(struct.jd);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(WD_FIELD_DESC);
      oprot.writeI32(struct.wd);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(SSSD_FIELD_DESC);
      oprot.writeByte(struct.sssd);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(FXJ_FIELD_DESC);
      oprot.writeI16(struct.fxj);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(GD_FIELD_DESC);
      oprot.writeI16(struct.gd);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(YYZT_FIELD_DESC);
      oprot.writeByte(struct.yyzt);
      oprot.writeFieldEnd();
      if (struct.kh != null) {
        oprot.writeFieldBegin(KH_FIELD_DESC);
        oprot.writeString(struct.kh);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(KQLX_FIELD_DESC);
      oprot.writeByte(struct.kqlx);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(KQFS_FIELD_DESC);
      oprot.writeByte(struct.kqfs);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class SKSJDTOTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public SKSJDTOTupleScheme getScheme() {
      return new SKSJDTOTupleScheme();
    }
  }

  private static class SKSJDTOTupleScheme extends org.apache.thrift.scheme.TupleScheme<SKSJDTO> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, SKSJDTO struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetActionCMDType()) {
        optionals.set(0);
      }
      if (struct.isSetXlid()) {
        optionals.set(1);
      }
      if (struct.isSetXlbh()) {
        optionals.set(2);
      }
      if (struct.isSetXlmc()) {
        optionals.set(3);
      }
      if (struct.isSetClid()) {
        optionals.set(4);
      }
      if (struct.isSetEmpId()) {
        optionals.set(5);
      }
      if (struct.isSetSbsxzch()) {
        optionals.set(6);
      }
      if (struct.isSetSksj()) {
        optionals.set(7);
      }
      if (struct.isSetJd()) {
        optionals.set(8);
      }
      if (struct.isSetWd()) {
        optionals.set(9);
      }
      if (struct.isSetSssd()) {
        optionals.set(10);
      }
      if (struct.isSetFxj()) {
        optionals.set(11);
      }
      if (struct.isSetGd()) {
        optionals.set(12);
      }
      if (struct.isSetYyzt()) {
        optionals.set(13);
      }
      if (struct.isSetKh()) {
        optionals.set(14);
      }
      if (struct.isSetKqlx()) {
        optionals.set(15);
      }
      if (struct.isSetKqfs()) {
        optionals.set(16);
      }
      oprot.writeBitSet(optionals, 17);
      if (struct.isSetActionCMDType()) {
        oprot.writeI32(struct.actionCMDType.getValue());
      }
      if (struct.isSetXlid()) {
        oprot.writeString(struct.xlid);
      }
      if (struct.isSetXlbh()) {
        oprot.writeString(struct.xlbh);
      }
      if (struct.isSetXlmc()) {
        oprot.writeString(struct.xlmc);
      }
      if (struct.isSetClid()) {
        oprot.writeString(struct.clid);
      }
      if (struct.isSetEmpId()) {
        oprot.writeString(struct.empId);
      }
      if (struct.isSetSbsxzch()) {
        oprot.writeString(struct.sbsxzch);
      }
      if (struct.isSetSksj()) {
        oprot.writeI32(struct.sksj);
      }
      if (struct.isSetJd()) {
        oprot.writeI32(struct.jd);
      }
      if (struct.isSetWd()) {
        oprot.writeI32(struct.wd);
      }
      if (struct.isSetSssd()) {
        oprot.writeByte(struct.sssd);
      }
      if (struct.isSetFxj()) {
        oprot.writeI16(struct.fxj);
      }
      if (struct.isSetGd()) {
        oprot.writeI16(struct.gd);
      }
      if (struct.isSetYyzt()) {
        oprot.writeByte(struct.yyzt);
      }
      if (struct.isSetKh()) {
        oprot.writeString(struct.kh);
      }
      if (struct.isSetKqlx()) {
        oprot.writeByte(struct.kqlx);
      }
      if (struct.isSetKqfs()) {
        oprot.writeByte(struct.kqfs);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, SKSJDTO struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(17);
      if (incoming.get(0)) {
        struct.actionCMDType = ActionCMDType.findByValue(iprot.readI32());
        struct.setActionCMDTypeIsSet(true);
      }
      if (incoming.get(1)) {
        struct.xlid = iprot.readString();
        struct.setXlidIsSet(true);
      }
      if (incoming.get(2)) {
        struct.xlbh = iprot.readString();
        struct.setXlbhIsSet(true);
      }
      if (incoming.get(3)) {
        struct.xlmc = iprot.readString();
        struct.setXlmcIsSet(true);
      }
      if (incoming.get(4)) {
        struct.clid = iprot.readString();
        struct.setClidIsSet(true);
      }
      if (incoming.get(5)) {
        struct.empId = iprot.readString();
        struct.setEmpIdIsSet(true);
      }
      if (incoming.get(6)) {
        struct.sbsxzch = iprot.readString();
        struct.setSbsxzchIsSet(true);
      }
      if (incoming.get(7)) {
        struct.sksj = iprot.readI32();
        struct.setSksjIsSet(true);
      }
      if (incoming.get(8)) {
        struct.jd = iprot.readI32();
        struct.setJdIsSet(true);
      }
      if (incoming.get(9)) {
        struct.wd = iprot.readI32();
        struct.setWdIsSet(true);
      }
      if (incoming.get(10)) {
        struct.sssd = iprot.readByte();
        struct.setSssdIsSet(true);
      }
      if (incoming.get(11)) {
        struct.fxj = iprot.readI16();
        struct.setFxjIsSet(true);
      }
      if (incoming.get(12)) {
        struct.gd = iprot.readI16();
        struct.setGdIsSet(true);
      }
      if (incoming.get(13)) {
        struct.yyzt = iprot.readByte();
        struct.setYyztIsSet(true);
      }
      if (incoming.get(14)) {
        struct.kh = iprot.readString();
        struct.setKhIsSet(true);
      }
      if (incoming.get(15)) {
        struct.kqlx = iprot.readByte();
        struct.setKqlxIsSet(true);
      }
      if (incoming.get(16)) {
        struct.kqfs = iprot.readByte();
        struct.setKqfsIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

